name: Package and Release

on:
  push:
    tags:
    - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build static
      uses:  stevenleadbeater/rust-musl-builder@master
      with:
          args: /bin/bash -c "cargo build --release --target=x86_64-unknown-linux-musl"
    - name: Archive Linux build
      uses: actions/upload-artifact@v2
      with:
        name: musl-test
        path: target/x86_64-unknown-linux-musl/release/musl-test
        retention-days: 5
